apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: wg9v30dvr-nodejs
  janus-idp.io/tekton: wg9v30dvr-nodejs
  backstage.io/kubernetes-id: wg9v30dvr-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: wg9v30dvr-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
