apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: wg9v30dvr-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: wg9v30dvr-nodejs 
  name: wg9v30dvr-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: wg9v30dvr-nodejs 
